#   #####################################################
#   #####BANCO DE DADOS###### NOME: mysql-server ########
#   #####################################################
# mysql-server:
#   image: mariadb:latest
#   command: --character-set-server=utf8 --collation-server=utf8_bin
#   # ports:
#   #   - 3306:3306
#   volumes:
#     - /home/cgoncalves/github/projectone/cesar/zabbix/banco:/var/lib/mysql
#   environment:
#     - MYSQL_HOST=mysql-server
#     - MYSQL_DATABASE=zabbix
#     - MYSQL_USER=zabbix
#     - MYSQL_PASSWORD=zabbix
#     - MYSQL_ROOT_PASSWORD=root
#     #####################################################
#     ####SERVIDOR ZABBIX###### NOME: zabbix-server #######
#     #####################################################
zabbix-server:
  image: zabbix/zabbix-server-mysql:ubuntu-4.0-latest
  expose:
    - "10051"
  environment:
    - DB_SERVER_ROOT_USER=admin
    - DB_SERVER_ROOT_PASS=bionexo2019
    # - MYSQL_ROOT_PASSWORD=root
    - DB_SERVER_HOST=zabbix-dev.c35pkwhpejsl.us-west-2.rds.amazonaws.com
    - DB_SERVER_PORT=3306
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=bionexo2019
    - MYSQL_DATABASE=zabbix
  # links:
  #   - mysql-server
      #####################################################
      ####FRONTEND DO ZABBIX###### NOME: zabbix-web #######
      #####################################################
zabbix-web:
  image: zabbix/zabbix-web-apache-mysql:ubuntu-4.0-latest
  ports:
    - 80:80
  environment:
    - DB_SERVER_HOST=zabbix-dev.c35pkwhpejsl.us-west-2.rds.amazonaws.com
    - DB_SERVER_PORT=3306
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=bionexo2019
    - MYSQL_DATABASE=zabbix
    - ZBX_SERVER_HOST=zabbix-server
    - PHP_TZ=America/Sao_Paulo
  links:
    # - mysql-server
    - zabbix-server
      #####################################################
      #####AGENTE ZABBIX###### NOME: zabbix-agent #########
      #####################################################
zabbix-agent:
  image: zabbix/zabbix-agent:ubuntu-4.0-latest
  hostname: zabbix-server-agent
  privileged: "true"
  volumes:
    - ./zabbix/agent-run:/var/run
  ports:
    - 10050:10050
  environment:
    # - ZBX_HOSTNAME="zabbix-server"
    - ZBX_SERVER_HOST=zabbix-server
  links:
    - zabbix-server