FROM zabbix/zabbix-server-mysql:latest
MAINTAINER Cesar Balboa
ENV TZ=America/Sao_Paulo

#Servidor MySQL
ENV DB_SERVER_HOST=zabbix-db.dev.cloud.bionexo.com.br
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=GWMcwyo8GjbH47nL