  #####################################################
  #####BANCO DE DADOS###### NOME: mysql-server ########
  #####################################################
mysql-server:
  image: mariadb:latest
  command: --character-set-server=utf8 --collation-server=utf8_bin
  # ports:
  #   - 3306:3306
  volumes:
    - /home/cgoncalves/github/projectone/cesar/zabbix/banco:/var/lib/mysql
  environment:
    - MYSQL_HOST=mysql-server
    - MYSQL_DATABASE=zabbix
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix
    - MYSQL_ROOT_PASSWORD=root
    #####################################################
    ####SERVIDOR ZABBIX###### NOME: zabbix-server #######
    #####################################################
zabbix-server:
  image: zabbix/zabbix-server-mysql:ubuntu-4.0-latest
  expose:
    - "10051"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - DB_SERVER_HOST=mysql-server
    - DB_SERVER_PORT=3306
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix
    - MYSQL_DATABASE=zabbix
  links:
    - mysql-server
      #####################################################
      ####FRONTEND DO ZABBIX###### NOME: zabbix-web #######
      #####################################################
zabbix-web:
  image: zabbix/zabbix-web-apache-mysql:ubuntu-4.0-latest
  ports:
    - 80:80
  environment:
    - DB_SERVER_HOST=mysql-server
    - DB_SERVER_PORT=3306
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix
    - MYSQL_DATABASE=zabbix
    - ZBX_SERVER_HOST=zabbix-server
    - PHP_TZ="America/Sao_Paulo"
  links:
    - mysql-server
    - zabbix-server
      #####################################################
      #####AGENTE ZABBIX###### NOME: zabbix-agent #########
      #####################################################
# zabbix-agent:
#   image: zabbix/zabbix-agent:ubuntu-4.0-latest
#   hostname: zabbix-server-agent
#   privileged: true
#   volumes:
#     - /home/cgoncalves/github/projectone/cesar/zabbix/agent-run:/var/run
#   ports:
#     - 10050:10050
#   environment:
#     - ZBX_HOSTNAME=localhost
#     - ZBX_SERVER_HOST=zabbix-server
#   links:
#     - zabbix-server